### PR TITLE
Add support for media_url

### PR DESCRIPTION
**Pull request by vinibaggio**
Hi! I made this customization where we can send a media_url in the data field and it will send a subsequent video or image to the whatsapp message. Also, my linter changed a bunch of things, and I can remove if these changes are unwelcomed. 

Thanks for creating this!

### CODE REVIEW

**Comment by ChrAnd2** [comment]
Im currently using this version. 
Works great, thanks for your effort! :) 

Would be nice if multiple Images are possible, or, the title and message are note mandatory anymore (guess thats not possible)
Probably as a multiline definition?
data:
  media_url: |
    https://link1....
    https://link2....

**Comment by vinibaggio** [comment]
@ChrAnd2 this shouldn't be hard to do, my time is a little limited right now but if you're interested in doing it yourself I can help

**Comment by ChrAnd2** [comment]
@vinibaggio u were completely right. 
Wasnt even thinking about doing it myself! :)
Quickly implemented it and opened a Pull Request :)

**Comment by vinibaggio** [comment]
@ChrAnd2 merged, thank you!

**Comment by t0mer** [comment]
Thank you both @vinibaggio  and @ChrAnd2

**Pull request merged**
